// The live VanikGPT's own places, in the prototype: Workspace, Notes, Calendar, Automations, Playground, Admin Panel and Settings.
// Every setting the live build shows is listed here from the audit (prod_schema.json). Settings that change how this build
// behaves are marked; the rest are kept and shown.
import { S, $, esc, icon, info, chip, go, ago, when, api, refresh, rerender, acts, ins, toast, modal, menu, confirmBox, navToggle, downloadText, applyTheme, initials, ROLE, signOut } from './core.js';
import { gptShell, gptPage } from './gpt.js';
import { libraryPage } from './more.js';

const P = { schema: null, data: null, key: '', vals: {}, extra: {}, play: { sys: '', msgs: [{ role: 'user', content: '' }], text: '', busy: false, ctx: false }, month: 0 };
export const parityRouteChanged = () => { P.key = ''; };
async function load() {
  try { if (!P.schema) P.schema = await (await fetch('prod_schema.json')).json(); P.data = await api('GET', '/api/parity'); P.vals = {}; rerender(); } catch (e) { toast(e.message, 'err'); }
}
const need = k => { if (P.key !== k) { P.key = k; load(); } return P.schema && P.data; };
const slugTab = t => t.toLowerCase().replace(/\W+/g, '-');
const shell = (active, title, actions, body, wide) => gptShell(active, `<div class="gpt-top">${navToggle()}<h3 class="grow">${title}</h3>${actions || ''}</div><div class="scroll" id="scroll"><div class="page" ${wide ? 'style="max-width:1180px"' : ''}>${body}</div></div>`);
const tabs = (items, on, base) => `<nav class="tabs" style="margin-bottom:20px">${items.map(t => `<a class="${t[0] === on ? 'on' : ''}" href="${base}/${t[0]}">${t[1]}${t[2] !== undefined ? ` <span class="mono">${t[2]}</span>` : ''}</a>`).join('')}</nav>`;

// ---------- one way to draw any list of settings
function form(fields, scope, saved, wiredKeys = []) {
  const cur = P.vals[scope] = P.vals[scope] || {}, val = f => f.key in cur ? cur[f.key] : saved && f.key in saved ? saved[f.key] : f.value;
  return fields.map(f => {
    const v = val(f), tip = f.help ? info(f.help) : '', live = wiredKeys.includes(f.key) ? `<span class="live-dot" data-tip="This one works in this build"></span>` : '', at = `data-s="${scope}" data-k="${f.key}"`;
    const ctl = f.kind === 'switch' ? `<button class="switch ${v ? 'on' : ''}" role="switch" aria-checked="${!!v}" aria-label="${esc(f.label)}" data-act="pf-sw" ${at}></button>`
      : f.kind === 'select' ? `<select class="input" style="width:230px" data-change="pf" ${at} aria-label="${esc(f.label)}">${(f.options || []).map(o => `<option ${o === v ? 'selected' : ''}>${esc(o)}</option>`).join('')}</select>`
      : f.kind === 'longtext' ? '' : `<input class="input" style="width:230px" type="${f.kind === 'number' ? 'number' : f.kind === 'secret' ? 'password' : 'text'}" value="${esc(v ?? '')}" placeholder="${esc(f.hint || '')}" data-on="pf" ${at} aria-label="${esc(f.label)}" ${f.kind === 'secret' ? 'autocomplete="off"' : ''}>`;
    return `<div class="set-row" ${f.kind === 'longtext' ? 'style="flex-wrap:wrap"' : ''}><div class="grow"><div class="lbl">${esc(f.label)} ${tip}${live}</div></div>${ctl}${f.kind === 'longtext' ? `<textarea class="input" rows="3" style="flex:1 1 100%;margin-top:8px" placeholder="${esc(f.hint || '')}" data-on="pf" ${at} aria-label="${esc(f.label)}">${esc(v ?? '')}</textarea>` : ''}</div>`;
  }).join('');
}
ins.pf = el => { (P.vals[el.dataset.s] = P.vals[el.dataset.s] || {})[el.dataset.k] = el.type === 'number' ? +el.value : el.value; };
acts['pf-sw'] = el => { const s = P.vals[el.dataset.s] = P.vals[el.dataset.s] || {}; const on = !el.classList.contains('on'); s[el.dataset.k] = on; el.classList.toggle('on', on); el.setAttribute('aria-checked', on); };
const saveBtn = (act, extra = '') => `<div class="row" style="margin-top:18px"><button class="btn" data-act="${act}" ${extra}>Save</button><span class="small faint">Settings with a green dot change how this build behaves. The others are kept and shown.</span></div>`;

// ---------- Workspace: Models, Knowledge, Prompts, Skills, Tools
const WS = [['models', 'Models'], ['knowledge', 'Knowledge'], ['prompts', 'Prompts'], ['skills', 'Skills'], ['tools', 'Tools']];
const wsTabs = on => { const B = S.boot, d = P.data || { tools: [] }, n = { models: B.assistants.length, knowledge: B.collections.filter(c => B.gptCollectionIds.includes(c.id)).length, prompts: B.prompts.length, skills: P.extra.skills ?? '', tools: d.tools.length }; return tabs(WS.map(t => [t[0], t[1], n[t[0]]]), on, '#/gpt/workspace'); };
const inject = (html, bar) => html.replace(/<div class="page"[^>]*>/, m => m + bar);
const CAPS = ['Vision', 'File Upload', 'File Context', 'Web Search', 'Image Generation', 'Code Interpreter', 'Terminal', 'Usage', 'Citations', 'Status Updates', 'Memory', 'Builtin Tools'], FEATS = ['Web Search', 'Image Generation', 'Code Interpreter'],
  BUILTIN = ['Time & Calculation', 'Ask User', 'Memory', 'Chat History', 'Notes', 'Knowledge Base', 'Files', 'Channels', 'Notifications', 'Web Search', 'Image Generation', 'Code Interpreter', 'Task Management', 'Automations', 'Calendar', 'Sub-agents'],
  PARAMS = ['Stream Chat Response', 'Stream Delta Chunk Size', 'Context Compaction Threshold', 'Function Calling', 'Reasoning Tags', 'Seed', 'Stop Sequence', 'Temperature', 'Reasoning Effort', 'logit_bias', 'max_tokens', 'top_k', 'top_p', 'min_p', 'frequency_penalty', 'presence_penalty', 'mirostat', 'mirostat_eta', 'mirostat_tau', 'repeat_last_n', 'tfs_z', 'repeat_penalty', 'use_mmap', 'use_mlock', 'think (Ollama)', 'format (Ollama)', 'num_keep (Ollama)', 'num_ctx (Ollama)', 'num_batch (Ollama)', 'num_thread (Ollama)', 'num_gpu (Ollama)', 'keep_alive (Ollama)'];
const k = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '_');
function modelLive(id) {
  const a = S.boot.assistants.find(x => x.id === id);
  if (!a) return shell('workspace', 'Workspace', '', wsTabs('models') + `<div class="empty">${icon('smart_toy')}This agent is gone.</div>`);
  const L = a.live || {}, sw = (list, group, def) => `<div class="row wrap" style="gap:8px">${list.map(x => { const on = (P.vals['m-' + group] = P.vals['m-' + group] || {})[k(x)] ?? (L[group] || {})[k(x)] ?? def(x); return `<button class="tag ${on ? 'on' : ''}" data-act="ml-tag" data-g="${group}" data-k="${k(x)}">${esc(x)}</button>`; }).join('')}</div>`;
  return shell('workspace', `<a href="#/gpt/workspace/models">Workspace</a> / ${esc(a.name)}`, `<a class="btn ghost" href="#/gpt/assistants/${a.id}">Name, instructions, knowledge</a><button class="btn" data-act="ml-save" data-id="${a.id}">Save</button>`, `<div class="stack" style="max-width:820px;gap:16px">
    <div class="banner plain">${icon('info_outline')}<span>These are the model settings the live VanikGPT has on its create form. They are kept with the agent. Its name, instructions, knowledge and plugins are on the other screen.</span></div>
    <div class="card"><div class="card-head"><h3>Capabilities</h3>${info('What the model is allowed to do in a chat.')}</div>${sw(CAPS, 'caps', x => x !== 'Usage')}</div>
    <div class="card"><div class="card-head"><h3>Default features</h3>${info('Turned on by default when a chat starts with this agent.')}</div>${sw(FEATS, 'feats', () => false)}</div>
    <div class="card"><div class="card-head"><h3>Built-in tools</h3>${info('Tools the model can call by itself. In this build the matching plugins are chosen on the agent screen.')}</div>${sw(BUILTIN, 'builtin', () => true)}</div>
    <div class="card"><div class="card-head"><h3>Advanced params</h3>${info('Leave a box empty to keep the default.')}</div><div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px">${PARAMS.map(x => `<label class="field"><span class="mono">${esc(x)}</span><input class="input" placeholder="Default" value="${esc(((P.vals['m-params'] || {})[k(x)]) ?? (L.params || {})[k(x)] ?? '')}" data-on="pf" data-s="m-params" data-k="${k(x)}"></label>`).join('')}</div></div>
    <div class="card"><label class="field"><span>TTS voice</span><input class="input" style="max-width:300px" placeholder="e.g. alloy, echo, shimmer" value="${esc((P.vals['m-misc'] || {}).voice ?? L.voice ?? '')}" data-on="pf" data-s="m-misc" data-k="voice"></label></div>
    <details class="card"><summary><h3 style="display:inline">JSON preview</h3></summary><pre class="code" style="margin-top:12px;white-space:pre-wrap">${esc(JSON.stringify({ id: a.id, name: a.name, base_model_id: a.model || S.boot.app.config.defaultModel, params: { system: a.instructions, ...(L.params || {}) }, meta: { description: a.description, capabilities: L.caps || {}, suggestion_prompts: a.starters } }, null, 2))}</pre></details></div>`);
}
acts['ml-tag'] = el => { const g = P.vals['m-' + el.dataset.g] = P.vals['m-' + el.dataset.g] || {}; const on = !el.classList.contains('on'); g[el.dataset.k] = on; el.classList.toggle('on', on); };
acts['ml-save'] = async el => { const a = S.boot.assistants.find(x => x.id === el.dataset.id), L = a.live || {}; const params = { ...(L.params || {}), ...(P.vals['m-params'] || {}) }; for (const x in params) if (params[x] === '') delete params[x]; await api('PUT', '/api/assistants/' + a.id, { ...a, live: { caps: { ...(L.caps || {}), ...(P.vals['m-caps'] || {}) }, feats: { ...(L.feats || {}), ...(P.vals['m-feats'] || {}) }, builtin: { ...(L.builtin || {}), ...(P.vals['m-builtin'] || {}) }, params, voice: (P.vals['m-misc'] || {}).voice ?? L.voice ?? '' } }); P.vals = {}; toast('Model settings saved.'); await refresh(); };
function promptEdit(p = {}) {
  modal({ title: p.id ? 'Prompt' : 'Create prompt', wide: true, body: `<div class="stack"><div class="row" style="gap:12px;align-items:flex-end"><label class="field grow"><span>Name</span><input class="input" id="p-title" maxlength="60" value="${esc(p.title || '')}"></label><label class="field"><span>Command ${info('Type / and this word in the message box to use the prompt.')}</span><input class="input" id="p-cmd" maxlength="30" placeholder="summarise" value="${esc(p.command || '')}"></label></div>
    <label class="field"><span>Prompt content ${info('Use {{variable}} for the parts to fill in each time.')}</span><textarea class="input" id="p-text" rows="6" placeholder="Write a summary in 50 words that summarizes {{topic}}.">${esc(p.text || '')}</textarea></label>
    <label class="field"><span>Tags</span><input class="input" id="p-tags" placeholder="finance, summary" value="${esc((p.tags || []).join(', '))}"></label>${S.boot.admin ? `<label class="row" style="gap:8px"><input type="checkbox" id="p-shared" ${p.shared ? 'checked' : ''}> Everyone can use this prompt</label>` : ''}</div>`,
    actions: [{ label: p.id ? 'Save' : 'Save and create', run: async o => { if (p.id) await api('DELETE', '/api/prompts/' + p.id); await api('POST', '/api/prompts', { title: $('#p-title', o).value, command: $('#p-cmd', o).value, text: $('#p-text', o).value, tags: $('#p-tags', o).value.split(','), shared: $('#p-shared', o) ? $('#p-shared', o).checked : false }); await refresh(); } }] });
}
acts['ws-prompt-new'] = () => promptEdit();
acts['ws-prompt-open'] = el => promptEdit(S.boot.prompts.find(p => p.id === el.dataset.id));
acts['ws-prompt-del'] = el => confirmBox('Delete this prompt?', 'It is removed for everyone who could use it.', 'Delete', async () => { await api('DELETE', '/api/prompts/' + el.dataset.id); await refresh(); });
function codeEdit(kind, x = {}) {
  const tpl = kind === 'tools' ? P.schema.toolTemplate : P.schema.functionTemplate, what = kind === 'tools' ? 'tool' : 'function';
  modal({ title: x.id ? `Change ${what}` : `Create ${what}`, wide: true, body: `<div class="stack"><div class="row" style="gap:12px"><label class="field grow"><span>Name</span><input class="input" id="c-name" maxlength="60" value="${esc(x.name || '')}"></label><label class="field"><span>ID</span><input class="input" id="c-slug" maxlength="40" value="${esc(x.slug || '')}" placeholder="my_${what}"></label></div>
    <label class="field"><span>Description</span><input class="input" id="c-desc" maxlength="200" value="${esc(x.description || '')}"></label>
    <label class="field"><span>Python ${info(`The live build runs this code inside the app. This build keeps it and lists it but does not run it; the plugins and tool connectors do that job here.`)}</span><textarea class="input mono" id="c-code" rows="12" spellcheck="false" style="font-size:12px;white-space:pre">${esc(x.code || tpl || '')}</textarea></label>
    ${kind === 'tools' && S.boot.admin ? `<label class="row" style="gap:8px"><input type="checkbox" id="c-shared" ${x.shared ? 'checked' : ''}> Everyone can pick this tool</label>` : ''}</div>`,
    actions: [{ label: 'Save', run: async o => { await api(x.id ? 'PUT' : 'POST', `/api/parity/${kind}` + (x.id ? '/' + x.id : ''), { name: $('#c-name', o).value, slug: $('#c-slug', o).value, description: $('#c-desc', o).value, code: $('#c-code', o).value, shared: $('#c-shared', o) ? $('#c-shared', o).checked : false, active: x.active !== false }); P.key = ''; rerender(); } }] });
}
acts['code-new'] = el => codeEdit(el.dataset.kind);
acts['code-open'] = el => codeEdit(el.dataset.kind, P.data[el.dataset.kind].find(x => x.id === el.dataset.id));
acts['code-del'] = el => confirmBox('Delete it?', 'This cannot be undone.', 'Delete', async () => { await api('DELETE', `/api/parity/${el.dataset.kind}/${el.dataset.id}`); P.key = ''; rerender(); });
const codeList = (kind, list, empty) => list.length ? `<div class="grid">${list.map(x => `<div class="card flat app-card" style="min-height:0"><div class="row"><span class="avatar sq">${icon(kind === 'tools' ? 'build' : 'functions')}</span><h3 class="grow ellipsis">${esc(x.name)}</h3><button class="icon-btn sm" data-act="code-del" data-kind="${kind}" data-id="${x.id}" aria-label="Delete">${icon('delete_outline')}</button></div><p class="small muted">${esc(x.description || 'No description')}</p><div class="row wrap" style="gap:6px">${chip(x.slug, 'line', false)}${chip('Kept, not run', 'line', false)}${x.shared ? chip('Shared', 'line', false) : ''}</div><div class="foot"><span class="small faint grow ellipsis">By ${esc(x.byName)}</span><button class="btn ghost" data-act="code-open" data-kind="${kind}" data-id="${x.id}">Open</button></div></div>`).join('')}</div>` : `<div class="empty">${icon(kind === 'tools' ? 'build' : 'functions')}${empty}</div>`;
export function workspacePage(parts) {
  const [tab = 'models', a] = parts; if (!need('ws')) return shell('workspace', 'Workspace', '', '<p class="muted">Loading…</p>');
  if (P.extra.skills === undefined) { P.extra.skills = ''; api('GET', '/api/skills').then(s => { P.extra.skills = s.length; rerender(); }).catch(() => {}); }
  if (tab === 'models' && a) return modelLive(a);
  if (tab === 'models') return inject(gptPage(['assistants']), wsTabs('models')).replace(/<h3 class="grow">Agents /, '<h3 class="grow">Workspace ');
  if (tab === 'knowledge') return inject(gptPage(['knowledge', a]), a ? '' : wsTabs('knowledge')).replace('<h3 class="grow">Knowledge ', '<h3 class="grow">Workspace ');
  if (tab === 'skills') return libraryPage('skills').replace(/<nav class="tabs"[\s\S]*?<\/nav>/, wsTabs('skills')).replace('<h3 class="grow">Library ', '<h3 class="grow">Workspace ');
  if (tab === 'prompts') { const l = S.boot.prompts; return shell('workspace', 'Workspace', `<button class="btn" data-act="ws-prompt-new">${icon('add')}New</button>`, wsTabs('prompts') + (l.length ? `<div class="card"><table class="list"><tr><th>Name</th><th>Command</th><th>Tags</th><th>By</th><th></th></tr>${l.map(p => `<tr><td><button class="link" data-act="ws-prompt-open" data-id="${p.id}">${esc(p.title)}</button><div class="small muted ellipsis" style="max-width:420px">${esc(p.text)}</div></td><td class="mono">${p.command ? '/' + esc(p.command) : ''}</td><td>${(p.tags || []).map(t => `<span class="tag">${esc(t)}</span>`).join(' ')}</td><td class="muted">${esc(p.byName || '')}${p.shared ? ' · shared' : ''}</td><td class="act">${S.boot.admin || p.userId === S.boot.me.id ? `<button class="icon-btn sm" data-act="ws-prompt-del" data-id="${p.id}" aria-label="Delete">${icon('delete_outline')}</button>` : ''}</td></tr>`).join('')}</table></div>` : `<div class="empty">${icon('bolt')}No prompts yet. A prompt is text you reuse, with {{variable}} for the parts that change.</div>`)); }
  return shell('workspace', 'Workspace', `<button class="btn" data-act="code-new" data-kind="tools">${icon('add')}New</button>`, wsTabs('tools') + codeList('tools', P.data.tools, 'No tools yet. On the live build a tool is Python code a model can call. Here, plugins and tool connectors do that job.'));
}

// ---------- Notes and Automations: the same lists as Library, at the places the live build has them
export const notesPage = () => libraryPage('notes').replace(/<nav class="tabs"[\s\S]*?<\/nav>/, '').replace('<h3 class="grow">Library ', '<h3 class="grow">Notes ');
export const automationsPage = () => libraryPage('automations').replace(/<nav class="tabs"[\s\S]*?<\/nav>/, '').replace('<h3 class="grow">Library ', '<h3 class="grow">Automations ');

// ---------- Calendar: events, tasks on their due day, automations on their next run
function eventEdit(e = {}) {
  const f = P.schema.forms.event, opt = l => ((f.find(x => x.label === l) || {}).options || []);
  modal({ title: e.id ? 'Event' : 'Create event', wide: true, body: `<div class="stack"><input class="input" id="e-title" maxlength="120" placeholder="Title" value="${esc(e.title || '')}">
    <div class="row wrap" style="gap:12px;align-items:flex-end"><label class="field"><span>Calendar</span><select class="input" id="e-cal"><option ${e.calendar !== 'Scheduled Tasks' ? 'selected' : ''}>Personal</option><option ${e.calendar === 'Scheduled Tasks' ? 'selected' : ''}>Scheduled Tasks</option></select></label><label class="field"><span>Starts</span><input class="input" type="datetime-local" id="e-start" value="${esc(e.start || P.extra.day || '')}"></label><label class="field"><span>Ends</span><input class="input" type="datetime-local" id="e-end" value="${esc(e.end || '')}"></label><label class="row" style="gap:6px;height:38px"><input type="checkbox" id="e-all" ${e.allDay ? 'checked' : ''}> All day</label></div>
    <div class="row wrap" style="gap:12px"><label class="field grow"><span>Location</span><input class="input" id="e-loc" value="${esc(e.location || '')}"></label><label class="field"><span>Reminder</span><select class="input" id="e-rem">${opt('Reminder').map(o => `<option>${esc(o)}</option>`).join('') || '<option>None</option>'}</select></label><label class="field"><span>Repeat</span><select class="input" id="e-rep">${opt('Repeat').map(o => `<option>${esc(o)}</option>`).join('') || '<option>Does not repeat</option>'}</select></label></div>
    <label class="field"><span>Description</span><textarea class="input" id="e-desc" rows="3">${esc(e.description || '')}</textarea></label></div>`,
    actions: [...(e.id ? [{ label: 'Delete', ghost: true, run: async () => { await api('DELETE', '/api/parity/events/' + e.id); P.key = ''; rerender(); } }] : []), { label: 'Save', run: async o => { await api(e.id ? 'PUT' : 'POST', '/api/parity/events' + (e.id ? '/' + e.id : ''), { title: $('#e-title', o).value, calendar: $('#e-cal', o).value, start: $('#e-start', o).value, end: $('#e-end', o).value, allDay: $('#e-all', o).checked, location: $('#e-loc', o).value, description: $('#e-desc', o).value }); P.key = ''; rerender(); } }] });
}
acts['ev-new'] = el => { P.extra.day = el.dataset.day ? el.dataset.day + 'T09:00' : ''; eventEdit(); };
acts['ev-open'] = el => eventEdit(P.data.events.find(e => e.id === el.dataset.id));
acts['cal-go'] = el => { P.month += +el.dataset.v; rerender(); };
export function calendarPage() {
  if (!need('cal')) return shell('calendar', 'Calendar', '', '<p class="muted">Loading…</p>');
  if (!P.extra.calKey) { P.extra.calKey = 1; Promise.all([api('GET', '/api/tasks'), api('GET', '/api/automations')]).then(([t, a]) => { P.extra.tasks = t; P.extra.autos = a; rerender(); }).catch(() => {}); }
  const base = new Date(); base.setDate(1); base.setMonth(base.getMonth() + P.month);
  const y = base.getFullYear(), mo = base.getMonth(), first = new Date(y, mo, 1).getDay(), days = new Date(y, mo + 1, 0).getDate(), key = d => `${y}-${String(mo + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`, today = new Date().toLocaleDateString('en-CA'), on = {};
  const put = (d, h) => { (on[d] = on[d] || []).push(h); };
  for (const e of P.data.events) put(e.start.slice(0, 10), `<button class="ev" data-act="ev-open" data-stop data-id="${e.id}" title="${esc(e.title)}">${e.allDay || e.start.length < 12 ? '' : esc(e.start.slice(11)) + ' '}${esc(e.title)}</button>`);
  for (const t of P.extra.tasks || []) if (t.due) put(t.due, `<a class="ev ${t.status}" href="#/gpt/tasks" title="${esc(t.title)}">${icon('task_alt')}${esc(t.title)}</a>`);
  for (const a of P.extra.autos || []) if (a.active && a.nextRunAt) put(new Date(a.nextRunAt).toLocaleDateString('en-CA'), `<a class="ev auto" href="#/gpt/automations" title="${esc(a.name)}">${icon('schedule')}${esc(a.name)}</a>`);
  const cells = [...Array(first).fill(0), ...Array.from({ length: days }, (_, i) => i + 1)];
  return shell('calendar', 'Tasks', `<div class="seg"><button data-act="task-view" data-v="list">List</button><button class="on" data-act="task-view" data-v="cal">Calendar</button></div><button class="btn" data-act="ev-new">${icon('add')}New event</button>`, `<div class="card"><div class="card-head"><button class="icon-btn sm" data-act="cal-go" data-v="-1" aria-label="Previous month">${icon('chevron_left')}</button><h3 style="min-width:150px;text-align:center">${base.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</h3><button class="icon-btn sm" data-act="cal-go" data-v="1" aria-label="Next month">${icon('chevron_right')}</button><span class="small muted right">Personal · Scheduled Tasks</span></div>
    <div class="cal">${['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => `<div class="dow">${d}</div>`).join('')}${cells.map(d => d ? `<div class="day ${key(d) === today ? 'today' : ''}" data-act="ev-new" data-day="${key(d)}" style="cursor:pointer"><span class="n">${d}</span>${(on[key(d)] || []).join('')}</div>` : '<div class="day off"></div>').join('')}</div></div>`, true);
}

// ---------- Playground: Chat, Completions, Images
async function gateway(messages) {
  const r = await fetch('/gateway/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-User': S.userId }, body: JSON.stringify({ model: P.play.model || S.boot.app.config.defaultModel, ...(P.play.ctx ? { use_context: true } : {}), messages }) }), j = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error((j.error && j.error.message) || 'The request failed.');
  return j.choices[0].message.content;
}
const keepPlay = () => { const s = $('#pg-sys'); if (s) P.play.sys = s.value; document.querySelectorAll('[data-pg]').forEach(t => { P.play.msgs[+t.dataset.pg].content = t.value; }); const c = $('#pg-text'); if (c) P.play.text = c.value; };
acts['pg-add'] = () => { keepPlay(); P.play.msgs.push({ role: P.play.msgs.length && P.play.msgs[P.play.msgs.length - 1].role === 'user' ? 'assistant' : 'user', content: '' }); rerender(); };
acts['pg-role'] = el => { keepPlay(); const m = P.play.msgs[+el.dataset.i]; m.role = m.role === 'user' ? 'assistant' : 'user'; rerender(); };
acts['pg-del'] = el => { keepPlay(); P.play.msgs.splice(+el.dataset.i, 1); rerender(); };
acts['pg-ctx'] = () => { keepPlay(); P.play.ctx = !P.play.ctx; rerender(); };
acts['pg-run'] = async el => { keepPlay(); P.play.busy = true; rerender(); try { if (el.dataset.mode === 'text') P.play.text += (P.play.text && !/\s$/.test(P.play.text) ? ' ' : '') + await gateway([{ role: 'user', content: 'Continue this text. Reply with the continuation only.\n\n' + P.play.text }]); else { const msgs = P.play.msgs.filter(m => m.content.trim()); if (!msgs.length) throw new Error('Write a message first.'); P.play.msgs.push({ role: 'assistant', content: await gateway([...(P.play.sys.trim() ? [{ role: 'system', content: P.play.sys }] : []), ...msgs]) }); } } catch (e) { toast(e.message, 'err'); } P.play.busy = false; rerender(); };
ins['pg-model'] = el => { P.play.model = el.value; };
export function playgroundPage(tab = 'chat') {
  const B = S.boot, models = B.app.config.models, pick = `<select class="input" style="width:220px" data-change="pg-model" aria-label="Model">${models.map(m => `<option ${m === (P.play.model || B.app.config.defaultModel) ? 'selected' : ''}>${esc(m)}</option>`).join('') || '<option>No model</option>'}</select>`;
  const bar = tabs([['chat', 'Chat'], ['completions', 'Completions'], ['images', 'Images']], tab, '#/gpt/playground');
  let body;
  if (tab === 'images') body = `<div class="empty">${icon('image')}Image generation is off, as it is on the live build. No image model is served on the appliance.${B.admin ? `<br><a class="btn ghost" href="#/gpt/admin/all/settings/images">Open the Images settings</a>` : ''}</div>`;
  else if (tab === 'completions') body = `<div class="card" style="max-width:820px"><textarea class="input" id="pg-text" rows="12" placeholder="Start writing. Run continues the text.">${esc(P.play.text)}</textarea><div class="row" style="margin-top:12px"><button class="btn" data-act="pg-run" data-mode="text" ${P.play.busy ? 'disabled' : ''}>${P.play.busy ? 'Running…' : 'Run'}</button></div></div>`;
  else body = `<div class="card" style="max-width:820px"><label class="field"><span>System instructions</span><textarea class="input" id="pg-sys" rows="2" placeholder="You are a helpful assistant.">${esc(P.play.sys)}</textarea></label>
      <div class="stack" style="gap:10px;margin-top:14px">${P.play.msgs.map((m, i) => `<div class="row" style="align-items:flex-start"><button class="tag" style="width:92px;justify-content:center" data-act="pg-role" data-i="${i}">${m.role === 'user' ? 'User' : 'Assistant'}</button><textarea class="input grow" rows="2" data-pg="${i}" placeholder="Enter ${m.role} message here">${esc(m.content)}</textarea><button class="icon-btn sm" data-act="pg-del" data-i="${i}" aria-label="Remove">${icon('close')}</button></div>`).join('')}</div>
      <div class="row" style="margin-top:12px"><button class="btn ghost" data-act="pg-add">${icon('add')}Add</button><button class="btn" data-act="pg-run" ${P.play.busy ? 'disabled' : ''}>${P.play.busy ? 'Running…' : 'Run'}</button><span class="small right">Use the knowledge base</span><button class="switch ${P.play.ctx ? 'on' : ''}" role="switch" aria-checked="${P.play.ctx}" aria-label="Use the knowledge base" data-act="pg-ctx"></button></div></div>`;
  return shell('playground', 'Playground', tab === 'images' ? '' : pick, bar + body);
}

// ---------- Admin Panel: Users, Evaluations, Functions, Settings
const ADMIN = [['users', 'Users'], ['evaluations', 'Evaluations'], ['functions', 'Functions'], ['settings', 'Settings']];
const adminTabs = on => tabs(ADMIN, on, '#/gpt/admin/all');
const side = (list, on, base) => `<div class="side-tabs">${list.map(t => `<a class="${t === on ? 'on' : ''}" href="${base}/${slugTab(t)}">${esc(t)}</a>`).join('')}</div>`;
acts['perm-open'] = () => modal({ title: 'Default permissions', wide: true, text: 'What people who are not admins may do. A group can widen this for its members.', body: `<div style="max-height:56vh;overflow:auto;padding-right:6px">${form(P.schema.forms.permissions, 'perms', P.data.permissions)}</div>`, actions: [{ label: 'Save', run: async () => { await api('PUT', '/api/parity/permissions', { values: { ...Object.fromEntries(P.schema.forms.permissions.map(f => [f.key, f.value])), ...P.data.permissions, ...(P.vals.perms || {}) } }); toast('Permissions saved.'); P.key = ''; rerender(); } }] });
acts['grp-edit'] = el => { const g = P.data.groups.find(x => x.name === el.dataset.name) || { name: '', members: [] }, ids = new Set(g.members.map(m => m.id)); const m = modal({ title: g.name ? 'Group' : 'New group', wide: true, body: `<div class="stack"><label class="field"><span>Name</span><input class="input" id="g-name" maxlength="40" value="${esc(g.name)}" ${g.name ? 'disabled' : ''}></label><div><div class="small" style="font-weight:600;margin-bottom:8px">Members</div><div class="row wrap" style="gap:6px" id="g-mem">${S.boot.users.map(u => `<button class="tag ${ids.has(u.id) ? 'on' : ''}" data-v="${u.id}">${esc(u.name)}</button>`).join('')}</div></div></div>`, actions: [...(g.name ? [{ label: 'Delete group', ghost: true, run: async () => { await api('DELETE', '/api/parity/groups/' + encodeURIComponent(g.name)); P.key = ''; await refresh(); } }] : []), { label: 'Save', run: async o => { await api('POST', '/api/parity/groups', { name: $('#g-name', o).value, members: [...o.querySelectorAll('#g-mem .on')].map(b => b.dataset.v) }); P.key = ''; await refresh(); } }] }); m.el.querySelector('#g-mem').addEventListener('click', e => { const b = e.target.closest('.tag'); if (b) b.classList.toggle('on'); }); };
acts['adm-save'] = async el => { const tab = el.dataset.tab, r = await api('PUT', '/api/parity/admin/' + encodeURIComponent(tab), { values: P.vals['adm-' + tab] || {} }); S.boot.flags = r.flags; toast(tab + ' saved.'); P.key = ''; await refresh(); };
acts['adm-export'] = async el => { try { if (el.dataset.v === 'users') downloadText('people.csv', (await api('GET', '/api/parity/export/users')).csv, 'text/csv'); else downloadText('all-chats.json', JSON.stringify(await api('GET', '/api/parity/export/all-chats'), null, 2), 'application/json'); } catch (e) { toast(e.message, 'err'); } };
function adminSettings(tabSlug) {
  const names = Object.keys(P.schema.admin), tab = names.find(n => slugTab(n) === tabSlug) || 'General', t = P.schema.admin[tab], wired = Object.values(P.data.wired).filter(w => w[0] === tab).map(w => w[1]);
  let panel = `<div class="card">${t.fields.length ? form(t.fields, 'adm-' + tab, P.data.admin[tab], wired) : ''}${t.fields.length ? saveBtn('adm-save', `data-tab="${esc(tab)}"`) : ''}</div>`;
  if (tab === 'Analytics') { if (!P.extra.an) { P.extra.an = 'loading'; api('GET', '/api/parity/analytics').then(a => { P.extra.an = a; rerender(); }); } const a = P.extra.an; panel = a && a !== 'loading' ? `<div class="grid four" style="margin-bottom:16px">${[['Messages', a.messages], ['Tokens', a.tokens.toLocaleString('en-IN')], ['Chats', a.chats], ['Users', a.users]].map(s => `<div class="card flat stat"><div class="k">${s[0]}</div><b>${s[1]}</b></div>`).join('')}</div><div class="card" style="margin-bottom:16px"><div class="card-head"><h3>Model usage</h3></div><table class="list"><tr><th>Model</th><th>Messages</th><th>Users</th><th>Chats</th><th>Tokens</th></tr>${a.models.map(m => `<tr><td>${esc(m.model)}</td><td>${m.messages}</td><td>${m.users}</td><td>${m.chats}</td><td>${m.tokens.toLocaleString('en-IN')}</td></tr>`).join('')}</table></div><div class="card"><div class="card-head"><h3>User activity</h3></div><table class="list"><tr><th>User</th><th>Messages</th><th>Tokens</th></tr>${a.people.map(m => `<tr><td>${esc(m.user)}</td><td>${m.messages}</td><td>${m.tokens.toLocaleString('en-IN')}</td></tr>`).join('')}</table><p class="small faint" style="margin-top:10px">Message counts are assistant answers. More is under <a class="link" href="#/os/apps/vanikgpt/usage">Usage in Vanik OS</a>.</p></div>` : '<p class="muted">Loading…</p>'; }
  if (tab === 'Database') panel = `<div class="card"><div class="set-row"><div class="grow"><div class="lbl">All chats ${info("Every person's chats as JSON. Works only when \"Admins can open people's chats\" is on in VanikGPT setup, and is written to the audit log.")}</div></div><button class="btn ghost" data-act="adm-export" data-v="chats">Export</button></div><div class="set-row"><div class="grow"><div class="lbl">Users ${info('Everyone on the tenant as CSV. Written to the audit log.')}</div></div><button class="btn ghost" data-act="adm-export" data-v="users">Export</button></div></div>`;
  if (tab === 'Pipelines') panel = `<div class="empty">${icon('account_tree')}No pipelines server is connected, as on the live build.</div>`;
  const note = { Models: `Which models people may pick is set in <a class="link" href="#/os/apps/vanikgpt/setup">VanikGPT setup</a> and served from the <a class="link" href="#/os/models">Model Hub</a>. ${S.boot.app.config.models.length} allowed now.`, Connections: `This build reaches models through the <a class="link" href="#/os/api-gateway">Vanik API gateway</a>, with a key issued on deploy. The live build points straight at the model server.`, Integrations: `Tool servers are <a class="link" href="#/os/connectors">tool connectors</a> in Vanik OS. Sign-ins for sites are in VanikGPT setup.`, Documents: `Collections live in the <a class="link" href="#/os/knowledge">Vanik OS knowledge base</a>, shared by every app.`, Authentication: `People sign in through Vanik OS. Roles and teams are under <a class="link" href="#/os/people">People</a>; who may use what is under <a class="link" href="#/os/access">Access</a>.`, 'Code Execution': 'Python runs in the browser, as on the live build.', Evaluations: `The board is under <a class="link" href="#/gpt/admin/all/evaluations">Evaluations</a>.` }[tab];
  return `<div class="two-pane">${side(names, tab, '#/gpt/admin/all/settings')}<div class="grow" style="min-width:0"><h2 style="margin-bottom:12px">${esc(tab)}</h2>${note ? `<div class="banner plain" style="margin-bottom:14px">${icon('info_outline')}<span>${note}</span></div>` : ''}${panel}</div></div>`;
}
export function adminPage(parts) {
  if (!S.boot.admin) return null;
  const [sec = 'users', a] = parts; if (!need('adm')) return shell('admin', 'Admin Panel', '', '<p class="muted">Loading…</p>');
  const B = S.boot; let body = '', actions = '';
  if (sec === 'users') {
    const sub = a === 'groups' ? 'groups' : 'overview';
    actions = sub === 'groups' ? `<button class="btn ghost" data-act="perm-open">Default permissions</button><button class="btn" data-act="grp-edit" data-name="">${icon('add')}New group</button>` : `<button class="btn" data-act="user-invite">${icon('add')}Add user</button>`;
    body = tabs([['overview', 'Overview', B.users.length], ['groups', 'Groups', P.data.groups.length]], sub, '#/gpt/admin/all/users') + (sub === 'groups'
      ? (P.data.groups.length ? `<div class="card">${P.data.groups.map(g => `<div class="set-row"><span class="avatar sq">${icon('groups')}</span><div class="grow"><div class="lbl">${esc(g.name)}</div><div class="small muted">${g.members.map(m => esc(m.name)).join(', ')}</div></div><span class="mono">${g.members.length}</span><button class="btn ghost" data-act="grp-edit" data-name="${esc(g.name)}">Open</button></div>`).join('')}</div>` : `<div class="empty">${icon('groups')}No groups yet. Use groups to give several people the same access.</div>`)
      : `<div class="card"><table class="list"><tr><th>Name</th><th>Role</th><th>Email</th><th>Last active</th><th>Created</th></tr>${B.users.map(u => `<tr><td><div class="row"><span class="avatar">${esc(initials(u.name))}</span><b>${esc(u.name)}</b></div></td><td>${chip(ROLE[u.role], u.role === 'user' ? 'line' : 'ok', false)}</td><td class="muted">${esc(u.email || '')}</td><td class="muted">${u.lastActiveAt ? ago(u.lastActiveAt) : u.status === 'invited' ? 'Invited' : ''}</td><td class="muted">${u.joinedAt ? when(u.joinedAt) : ''}</td></tr>`).join('')}</table><p class="small faint" style="margin-top:10px">Change a role, teams or remove someone under <a class="link" href="#/os/people">People in Vanik OS</a>.</p></div>`);
  } else if (sec === 'evaluations') {
    if (!P.extra.ev) { P.extra.ev = 'loading'; api('GET', '/api/parity/evaluations').then(e => { P.extra.ev = e; rerender(); }); }
    const e = P.extra.ev, sub = a === 'feedback' ? 'feedback' : 'leaderboard';
    body = e && e !== 'loading' ? tabs([['leaderboard', 'Leaderboard', e.board.length], ['feedback', 'Feedback', e.feedback.length]], sub, '#/gpt/admin/all/evaluations') + `<div class="card">${sub === 'feedback' ? (e.feedback.length ? `<table class="list"><tr><th>By</th><th>Model</th><th>Rating</th><th>Reason</th><th>When</th></tr>${e.feedback.map(f => `<tr><td>${esc(f.by)}</td><td>${esc(f.model)}</td><td>${chip(f.rating === 'up' ? 'Helpful' : 'Not helpful', f.rating === 'up' ? 'ok' : 'warn', false)}</td><td class="muted">${esc(f.reason)}</td><td class="muted">${ago(f.at)}</td></tr>`).join('')}</table>` : '<p class="muted">No feedback yet.</p>') : (e.board.length ? `<table class="list"><tr><th>#</th><th>Model</th><th>Rating</th><th>Helpful</th><th>Not helpful</th></tr>${e.board.map((b, i) => `<tr><td>${i + 1}</td><td><b>${esc(b.model)}</b></td><td>${b.score}</td><td>${b.up}</td><td>${b.down}</td></tr>`).join('')}</table><p class="small faint" style="margin-top:10px">Built from people's ratings of answers. Each helpful rating moves a model up, each not helpful one down.</p>` : '<p class="muted">No ratings yet.</p>')}</div>` : '<p class="muted">Loading…</p>';
  } else if (sec === 'functions') { actions = `<button class="btn" data-act="code-new" data-kind="functions">${icon('add')}New</button>`; body = codeList('functions', P.data.functions, 'No functions yet. On the live build a function is Python code that adds a model, a filter or an action.'); }
  else return shell('admin', 'Admin Panel', '', adminTabs('settings') + adminSettings(a || 'general'), true);
  return shell('admin', 'Admin Panel', actions, adminTabs(sec) + body, true);
}

// ---------- Settings for one person: 11 tabs
acts['me-save'] = async el => { const tab = el.dataset.tab, v = P.vals['me-' + tab] || {}; await api('PUT', '/api/parity/me/' + encodeURIComponent(tab), { values: v }); if (tab === 'General' && v.theme) { localStorage.setItem('vnk.theme', /dark/i.test(v.theme) ? 'dark' : /light/i.test(v.theme) ? 'light' : 'auto'); applyTheme(); } if (tab === 'Interface' && 'temporary_chat_by_default' in v) localStorage.setItem('vnk.tempDefault', v.temporary_chat_by_default ? '1' : ''); toast(tab + ' saved.'); P.key = ''; rerender(); };
acts['me-archive-all'] = () => confirmBox('Archive all chats?', 'They leave the list and can be brought back from Archived Chats.', 'Archive all', async () => { const r = await api('POST', '/api/parity/archive-all'); toast(`${r.archived} archived.`); P.key = ''; await refresh(); }, false);
acts['me-delete-all'] = () => confirmBox('Delete all your chats?', 'Every chat and the files attached to them are removed. This cannot be undone.', 'Delete all', async () => { const r = await api('DELETE', '/api/parity/my-chats'); toast(`${r.deleted} deleted.`); P.key = ''; await refresh(); });
acts['me-export'] = async () => downloadText('my-chats.json', JSON.stringify(await api('GET', '/api/parity/export/my-chats'), null, 2), 'application/json');
acts['me-unarchive'] = async el => { await api('PATCH', '/api/chats/' + el.dataset.id, { archived: false }); P.key = ''; await refresh(); };
export function settingsPage(tabSlug) {
  if (!need('me')) return shell('settings', 'Settings', '', '<p class="muted">Loading…</p>');
  if (!P.extra.memKey) { P.extra.memKey = 1; api('GET', '/api/memories').then(m => { P.extra.mem = m; rerender(); }).catch(() => {}); }
  const names = Object.keys(P.schema.me), tab = names.find(n => slugTab(n) === tabSlug) || 'General', t = P.schema.me[tab], me = S.boot.me, st = P.data.mine;
  const wired = tab === 'General' ? ['theme'] : tab === 'Interface' ? ['temporary_chat_by_default'] : [];
  const fields = t.fields.map(f => tab === 'General' && /theme/i.test(f.label + f.key) ? { ...f, key: 'theme' } : f);
  let panel = `<div class="card">${form(fields, 'me-' + tab, (P.data.me || {})[tab], wired)}${saveBtn('me-save', `data-tab="${esc(tab)}"`)}</div>`;
  if (tab === 'Personalization') panel = `<div class="card"><div class="card-head"><h3>Memory</h3>${info('Short lines added to your chats so answers fit you. Nobody else sees them.')}<button class="btn ghost right" data-act="mem-new">${icon('add')}Add memory</button></div>${(P.extra.mem || []).length ? P.extra.mem.map(m => `<div class="set-row"><div class="grow">${esc(m.text)}</div></div>`).join('') : '<p class="muted">Nothing saved yet.</p>'}<p class="small faint" style="margin-top:10px">Remove a line under <a class="link" href="#/gpt/library/memory">Library, Memory</a>.</p></div>`;
  if (tab === 'Data Controls') panel = `<div class="card"><div class="set-row"><div class="grow"><div class="lbl">Export chats</div><div class="small muted">Download your chat history as JSON.</div></div><button class="btn ghost" data-act="me-export">Export</button></div><div class="set-row"><div class="grow"><div class="lbl">Shared chats</div><div class="small muted">${S.boot.chats.filter(c => c.shared).length} shared now. Stop sharing from a chat's menu.</div></div></div><div class="set-row"><div class="grow"><div class="lbl">Archive all chats</div><div class="small muted">Move every chat into the archive.</div></div><button class="btn ghost" data-act="me-archive-all">Archive all</button></div><div class="set-row"><div class="grow"><div class="lbl">Delete all chats</div><div class="small muted">Permanently delete every chat.</div></div><button class="btn danger" data-act="me-delete-all">Delete all</button></div></div>`;
  if (tab === 'Usage') panel = `<div class="grid four" style="margin-bottom:16px">${[['Chats', st.chats], ['Your messages', st.questions], ['Answers', st.answers], ['Active days', st.days]].map(s => `<div class="card flat stat"><div class="k">${s[0]}</div><b>${s[1]}</b></div>`).join('')}</div><div class="card"><div class="set-row"><div class="grow"><div class="lbl">Tokens</div></div><b>${st.tokens.toLocaleString('en-IN')}</b></div><div class="set-row"><div class="grow"><div class="lbl">Models used</div></div><span class="muted">${st.models.map(esc).join(', ') || 'None yet'}</span></div><p class="small faint" style="margin-top:10px">Token counts are estimates.</p></div>`;
  if (tab === 'Archived Chats') panel = `<div class="card">${P.data.archived.length ? P.data.archived.map(c => `<div class="set-row"><div class="grow"><div class="lbl ellipsis">${esc(c.title)}</div><div class="small muted">${ago(c.updatedAt)}</div></div><button class="btn ghost" data-act="me-unarchive" data-id="${c.id}">Unarchive</button></div>`).join('') : '<p class="muted">You have no archived chats.</p>'}</div>`;
  if (tab === 'Account') panel = `<div class="card"><div class="row" style="margin-bottom:14px"><span class="avatar" style="width:44px;height:44px">${esc(initials(me.name))}</span><div><b>${esc(me.name)}</b><div class="small muted">${esc(me.email || '')} · ${ROLE[me.role]}</div></div></div>${form(fields.filter(f => !/password/i.test(f.label)), 'me-' + tab, (P.data.me || {})[tab])}${saveBtn('me-save', `data-tab="${esc(tab)}"`)}<p class="small faint" style="margin-top:10px">Your name, email and password belong to your Vanik OS account, so they are not changed here.</p></div>`;
  if (tab === 'About') panel = `<div class="card"><dl class="kv"><dt>VanikGPT</dt><dd>Prototype, built on the live build's structure</dd><dt>Live build audited</dt><dd>${esc(P.schema.source)} on ${esc(P.schema.capturedOn)}</dd><dt>Runs on</dt><dd>Your Vanik Appliance. Nothing leaves your network.</dd></dl></div>`;
  if (tab === 'Keyboard') panel = `<div class="card"><div class="kbd">${t.text.split(' | ').slice(4).reduce((a, x, i, all) => i % 2 === 0 && all[i + 1] !== undefined && all[i + 1].length < 26 && /[+\/@#*↑]|Esc|Tab|Unassigned/.test(all[i + 1]) ? a + `<div class="set-row"><div class="grow">${esc(x)}</div><span class="mono">${esc(all[i + 1])}</span></div>` : a, '')}</div><p class="small faint" style="margin-top:10px">The shortcuts of the live build. In this build: Ctrl K searches, Alt T changes the theme, / opens commands.</p></div>`;
  return shell('settings', 'Settings', '', `<div class="two-pane">${side(names, tab, '#/gpt/settings/all')}<div class="grow" style="min-width:0"><h2 style="margin-bottom:12px">${esc(tab)}</h2>${panel}</div></div>`, true);
}

export function applyFlags() { const f = (S.boot && S.boot.flags) || {}; document.body.classList.toggle('no-rating', f.rating === false); document.body.classList.toggle('no-code', f.code === false); document.body.classList.toggle('no-folders', f.folders === false); }
