// The simpler shape of VanikGPT: one place and one name for each thing.
//   Agents · Knowledge · Routines · Tasks · Saved, with Settings and Admin under your name.
// Routines gathers the three ways to "do this job again": checks on documents, replayed chat steps and scheduled questions.
// Settings and Admin show only what works; everything carried over from the live build sits behind Advanced.
import { S, $, esc, icon, info, chip, go, ago, api, refresh, rerender, acts, toast, modal, menu, navToggle, applyTheme, initials, ROLE, signOut } from './core.js';
import { gptShell } from './gpt.js';
import { LIB, loadLibrary } from './more.js';

const Z = { key: '', types: null, runs: null, filter: 'all', par: null, mem: null };
export const simpleRouteChanged = () => { Z.key = ''; };
const page = (active, title, tip, actions, body, width = 980) => gptShell(active, `<div class="gpt-top">${navToggle()}<h3 class="grow">${title} ${tip ? info(tip, 'tip-down') : ''}</h3>${actions || ''}</div><div class="scroll" id="scroll"><div class="page" style="max-width:${width}px">${body}</div></div>`);
const row = (ic, title, sub, href) => `<a class="go-row" href="${href}"><span class="avatar sq">${icon(ic)}</span><span class="grow"><b>${title}</b><span class="small muted">${sub}</span></span>${icon('chevron_right')}</a>`;

// ---------- Routines
const CHECKS = [['three_way', 'Three-way match', 'receipt_long', 'An invoice against its purchase order and goods receipt.'], ['kyc', 'Vendor KYC check', 'verified_user', "A vendor's PAN, GSTIN, bank and identity details against each other."], ['quotes', 'Quote comparison', 'compare_arrows', 'Quotes from several suppliers, lined up, with the lowest complete one.']];
const KIND = { check: ['Check', 'fact_check', 'Reads documents and checks them against exact rules.'], steps: ['Steps', 'bolt', 'Replays the steps of a chat that worked.'], schedule: ['Schedule', 'schedule', 'Asks a question for you every hour, day or week.'] };
acts['rt-filter'] = el => { Z.filter = el.dataset.v; rerender(); };
acts['rt-new'] = () => { const m = modal({ title: 'New routine', cancel: 'Close', text: 'A routine is a job VanikGPT does again for you. Pick how it starts.', body: `<div class="opts">
  <button class="opt" data-v="steps">${icon('bolt')}<span class="grow"><b>Replay the steps of a chat</b><span class="small muted">You can also save any chat as a routine from the menu under an answer.</span></span></button>
  <button class="opt" data-v="check">${icon('fact_check')}<span class="grow"><b>Check documents against rules</b><span class="small muted">List the documents and the rules. It stops for a person when a rule fails.</span></span></button>
  <button class="opt" data-v="schedule">${icon('schedule')}<span class="grow"><b>Ask on a schedule</b><span class="small muted">A question asked every hour, day or week. The answers collect in one chat.</span></span></button></div>` });
  m.el.querySelector('.opts').addEventListener('click', e => { const b = e.target.closest('.opt'); if (!b) return; m.close(); if (b.dataset.v === 'check') go('#/gpt/flows/build'); else acts[b.dataset.v === 'steps' ? 'skill-new' : 'auto-new'](); }); };
export function routinesPage() {
  if (Z.key !== 'rt') { Z.key = 'rt'; loadLibrary(); Promise.all([api('GET', '/api/workflow-types'), api('GET', '/api/workflows')]).then(([t, r]) => { Z.types = t; Z.runs = r; rerender(); }).catch(e => toast(e.message, 'err')); }
  const me = S.boot.me.id, ready = Z.types && LIB.skills && LIB.autos, f = Z.filter;
  const card = (kind, ic, name, sub, foot, action, more = '') => `<div class="card flat rt"><div class="row"><span class="avatar sq">${icon(ic)}</span><h3 class="grow ellipsis">${esc(name)}</h3>${more}</div><p class="small muted">${esc(sub)}</p><div class="foot">${chip(KIND[kind][0], 'line', false)}<span class="small faint grow ellipsis">${foot}</span>${action}</div></div>`;
  let cards = [];
  if (ready) {
    if (f === 'all' || f === 'check') cards = cards.concat(CHECKS.map(c => card('check', c[2], c[1], c[3], 'Built in', `<a class="btn ghost" href="#/gpt/flows/new/${c[0]}">Run</a>`)), Z.types.map(t => card('check', t.icon, t.name, t.description || `${t.rules.length} rules`, 'By ' + esc(t.createdByName), `<a class="btn ghost" href="#/gpt/flows/new/${encodeURIComponent('custom:' + t.id)}">Run</a>`, S.boot.admin || t.createdBy === me ? `<a class="icon-btn sm tip-left" href="#/gpt/flows/build/${t.id}" data-tip="Change" aria-label="Change">${icon('edit')}</a>` : '')));
    if (f === 'all' || f === 'steps') cards = cards.concat(LIB.skills.map(s => card('steps', 'bolt', s.name, s.description || s.steps[0], `${s.steps.length} ${s.steps.length === 1 ? 'step' : 'steps'}${s.shared ? ' · shared' : ''}`, `<button class="btn ghost" data-act="skill-run" data-id="${s.id}">Run</button>`, s.userId === me || S.boot.admin ? `<button class="icon-btn sm" data-act="skill-menu" data-id="${s.id}" aria-label="More">${icon('more_vert')}</button>` : '')));
    if ((f === 'all' || f === 'schedule') && (S.boot.flags || {}).automations !== false) cards = cards.concat(LIB.autos.map(a => card('schedule', 'schedule', a.name, a.lastResult || a.prompt, `Every ${a.every}${a.lastRunAt ? ' · ran ' + ago(a.lastRunAt) : ''}${a.active ? '' : ' · paused'}`, `<button class="btn ghost" data-act="auto-run" data-id="${a.id}">Run now</button>`, `<button class="icon-btn sm" data-act="auto-menu" data-id="${a.id}" aria-label="More">${icon('more_vert')}</button>`)));
  }
  const runs = (Z.runs || []).slice(0, 6);
  return page('routines', 'Routines', 'A job VanikGPT does again for you: a check on documents, the steps of a chat, or a question on a schedule.', `<button class="btn" data-act="rt-new">${icon('add')}New routine</button>`,
    `<div class="row" style="margin-bottom:18px"><div class="seg">${[['all', 'All'], ['check', 'Checks'], ['steps', 'Steps'], ['schedule', 'Schedules']].map(x => `<button class="${f === x[0] ? 'on' : ''}" data-act="rt-filter" data-v="${x[0]}">${x[1]}</button>`).join('')}</div>${f !== 'all' ? `<span class="small muted">${KIND[f][2]}</span>` : ''}</div>
    ${!ready ? '<p class="muted">Loading…</p>' : cards.length ? `<div class="grid">${cards.join('')}</div>` : `<div class="empty">${icon(KIND[f] ? KIND[f][1] : 'bolt')}Nothing here yet.<br><button class="btn" data-act="rt-new">New routine</button></div>`}
    ${runs.length ? `<div class="section-title" style="margin-top:28px"><h2>Recent checks</h2><a class="link small right" href="#/gpt/flows">See all</a></div><div class="card">${runs.map(w => `<a class="go-row" href="#/gpt/flows/${w.id}"><span class="grow"><b>${esc(w.title)}</b><span class="small muted">${esc(w.typeName)} · ${esc(w.createdByName)} · ${ago(w.createdAt)}</span></span>${chip(w.status === 'needs_approval' ? 'Waiting for a decision' : w.outcome, w.status === 'needs_approval' ? 'warn' : w.status === 'rejected' ? 'err' : 'ok', false)}</a>`).join('')}</div>` : ''}`, 1100);
}

// ---------- Saved: the prompts tab (notes and memory are drawn by the library)
export const promptsHtml = () => { const l = S.boot.prompts; return l.length ? `<div class="card">${l.map(p => `<div class="set-row"><div class="grow"><button class="link" data-act="ws-prompt-open" data-id="${p.id}"><b>${esc(p.title)}</b></button>${p.command ? ` <span class="mono">/${esc(p.command)}</span>` : ''}<div class="small muted ellipsis" style="max-width:640px">${esc(p.text)}</div></div>${p.shared ? chip('Shared', 'line', false) : ''}${S.boot.admin || p.userId === S.boot.me.id ? `<button class="icon-btn sm tip-left" data-act="ws-prompt-del" data-id="${p.id}" data-tip="Delete" aria-label="Delete">${icon('delete_outline')}</button>` : ''}</div>`).join('')}</div>` : `<div class="empty">${icon('bolt')}No prompts yet. A prompt is text you reuse. Pick one from the + menu in the message box.</div>`; };

// ---------- Settings: only what works. The live build's full list is one link away.
const loadMe = () => Promise.all([api('GET', '/api/parity'), api('GET', '/api/memories')]).then(([p, m]) => { Z.par = p; Z.mem = m; rerender(); }).catch(e => toast(e.message, 'err'));
acts['st-theme'] = el => { localStorage.setItem('vnk.theme', el.dataset.v); applyTheme(); rerender(); };
acts['st-temp'] = async () => { const on = localStorage.getItem('vnk.tempDefault') !== '1'; localStorage.setItem('vnk.tempDefault', on ? '1' : ''); await api('PUT', '/api/parity/me/Interface', { values: { temporary_chat_by_default: on } }); rerender(); };
acts['st-mem-del'] = async el => { await api('DELETE', '/api/memories/' + el.dataset.id); Z.key = ''; rerender(); };
acts['st-mem-add'] = () => modal({ title: 'Remember this', body: `<textarea class="input" id="m-text" rows="3" maxlength="300" placeholder="I work in plant maintenance in Pune."></textarea>`, actions: [{ label: 'Remember', run: async o => { await api('POST', '/api/memories', { text: $('#m-text', o).value }); Z.key = ''; rerender(); } }] });
export function settingsSimple() {
  if (Z.key !== 'st') { Z.key = 'st'; loadMe(); }
  const me = S.boot.me, th = localStorage.getItem('vnk.theme') || 'auto', p = Z.par, card = (title, tip, body) => `<div class="card"><div class="card-head"><h3>${title}</h3>${tip ? info(tip) : ''}</div>${body}</div>`;
  return page('settings', 'Settings', '', '', `<div class="stack" style="gap:16px">
    ${card('Look', '', `<div class="seg">${[['auto', 'Match my device'], ['light', 'Light'], ['dark', 'Dark']].map(x => `<button class="${th === x[0] ? 'on' : ''}" data-act="st-theme" data-v="${x[0]}">${x[1]}</button>`).join('')}</div>`)}
    ${card('Chats', '', `<div class="set-row"><div class="grow"><div class="lbl">Start new chats as temporary ${info('A temporary chat is not listed and is removed when you leave it.')}</div></div><button class="switch ${localStorage.getItem('vnk.tempDefault') === '1' ? 'on' : ''}" role="switch" aria-checked="${localStorage.getItem('vnk.tempDefault') === '1'}" aria-label="Start new chats as temporary" data-act="st-temp"></button></div>`)}
    ${(S.boot.flags || {}).memories === false ? '' : card('What VanikGPT remembers about you', 'Short lines added to your chats so answers fit you. Nobody else sees them.', `${!Z.mem ? '<p class="muted">Loading…</p>' : Z.mem.length ? Z.mem.map(m => `<div class="set-row"><div class="grow">${esc(m.text)}</div><button class="icon-btn sm tip-left" data-act="st-mem-del" data-id="${m.id}" data-tip="Forget" aria-label="Forget">${icon('close')}</button></div>`).join('') : '<p class="muted">Nothing yet.</p>'}<button class="btn ghost" style="margin-top:12px" data-act="st-mem-add">${icon('add')}Add</button>`)}
    ${card('Your data', '', `<div class="set-row"><div class="grow"><div class="lbl">Download my chats</div></div><button class="btn ghost" data-act="me-export">Download</button></div>
      <div class="set-row"><div class="grow"><div class="lbl">Archived chats</div><div class="small muted">${p ? p.archived.length : 0} archived</div></div>${p && p.archived.length ? `<button class="btn ghost" data-act="st-archived">Open</button>` : ''}<button class="btn ghost" data-act="me-archive-all">Archive all</button></div>
      <div class="set-row"><div class="grow"><div class="lbl">Delete all my chats</div></div><button class="btn danger" data-act="me-delete-all">Delete all</button></div>`)}
    ${card('Account', '', `<div class="row"><span class="avatar" style="width:44px;height:44px">${esc(initials(me.name))}</span><div class="grow"><b>${esc(me.name)}</b><div class="small muted">${esc(me.email || '')} · ${ROLE[me.role]}${(me.teams || []).length ? ' · ' + me.teams.map(esc).join(', ') : ''}</div></div><button class="btn ghost" data-act="st-switch">Switch account</button></div>`)}
    <a class="link small" href="#/gpt/settings/all">Advanced: every setting carried over from the live build</a></div>`, 760);
}
acts['st-switch'] = signOut;
acts['st-archived'] = () => modal({ title: 'Archived chats', wide: true, cancel: 'Close', body: Z.par.archived.map(c => `<div class="set-row"><div class="grow"><div class="lbl ellipsis">${esc(c.title)}</div><div class="small muted">${ago(c.updatedAt)}</div></div><button class="btn ghost" data-act="me-unarchive" data-id="${c.id}">Bring back</button></div>`).join('') });

// ---------- Admin: the switches that work, and one door to each admin job
const FEATURES = [['rating', 'General', 'message_rating', 'Helpful and not helpful on answers'], ['followUps', 'Interface', 'follow_up_generation', 'What to ask next, under an answer'], ['folders', 'General', 'folders', 'Folders for chats'], ['memories', 'General', 'memories', 'Memory'], ['notes', 'General', 'notes', 'Notes'], ['calendar', 'General', 'calendar', 'Calendar'], ['automations', 'General', 'automations', 'Routines on a schedule'], ['code', 'Code Execution', 'enable_code_execution', 'Python that runs in the browser']];
acts['ad-flag'] = async el => { const f = FEATURES.find(x => x[0] === el.dataset.k), on = (S.boot.flags || {})[f[0]] === false; const r = await api('PUT', '/api/parity/admin/' + encodeURIComponent(f[1]), { values: { [f[2]]: on } }); S.boot.flags = r.flags; toast(`${f[3]}: ${on ? 'on' : 'off'}.`); await refresh(); };
export function adminSimple() {
  if (!S.boot.admin) return null;
  const fl = S.boot.flags || {};
  return page('admin', 'Admin', '', '', `<div class="stack" style="gap:16px">
    <div class="card"><div class="card-head"><h3>What people can use</h3>${info('Turning one off hides it for everyone straight away.')}</div><div class="feature-grid">${FEATURES.map(f => `<div class="set-row"><div class="grow"><div class="lbl">${f[3]}</div></div><button class="switch ${fl[f[0]] !== false ? 'on' : ''}" role="switch" aria-checked="${fl[f[0]] !== false}" aria-label="${f[3]}" data-act="ad-flag" data-k="${f[0]}"></button></div>`).join('')}</div></div>
    <div class="card" style="padding:6px 8px">${row('tune', 'Setup', 'Models, knowledge, abilities, sign-ins for sites, safety and house rules', '#/os/apps/vanikgpt/setup')}${row('group', 'People and teams', 'Invite, set roles, put people in teams', '#/os/people')}${row('admin_panel_settings', 'Who can use what', 'Each collection, agent, ability, connector and routine', '#/os/access')}${row('bar_chart', 'Usage', 'Questions, people, how answers were made', '#/os/apps/vanikgpt/usage')}${row('thumbs_up_down', 'Ratings', "A board of models from people's ratings, and the ratings", '#/gpt/admin/all/evaluations')}${row('history', 'Activity', 'Versions, deploys and the audit log', '#/os/apps/vanikgpt/activity')}${row('api', 'For developers', 'API keys, playground, webhooks', '#/os/api-gateway')}</div>
    <details class="card"><summary><h3 style="display:inline">Advanced</h3> <span class="small muted">Carried over from the live build</span></summary><div style="margin-top:10px">${row('settings', 'All settings', 'The 16 tabs of the live build. Most are kept and shown, not acted on', '#/gpt/admin/all/settings')}${row('workspaces', 'Workspace', 'Models, prompts, skills and code tools as the live build lays them out', '#/gpt/workspace')}${row('functions', 'Functions', 'Python kept with the app. Not run in this build', '#/gpt/admin/all/functions')}${row('science', 'Playground', 'Chat, completions, images', '#/gpt/playground')}</div></details></div>`, 760);
}

// ---------- the menu under your name: two things, not eight
acts['user-menu'] = el => { const B = S.boot, inGpt = location.hash.startsWith('#/gpt') && B.canUseGpt, to = (label, ic, href) => ({ label, icon: ic, run: () => go(href) }); menu(el, [{ heading: B.me.email || B.me.name }, ...(inGpt ? [to('Settings', 'settings', '#/gpt/settings'), B.admin && to('Admin', 'admin_panel_settings', '#/gpt/admin'), B.admin && to('Vanik OS', 'dns', '#/os/home')] : B.canUseGpt ? [to('Open VanikGPT', 'forum', '#/gpt')] : []), '-', { label: 'Switch account', icon: 'swap_horiz', run: signOut }]); };
